export const padraoDict = {
    1: {'en': 'day', 'pt': 'dia', 'pt_': '---', 'en_': '---'},
    2: {'en': 'night', 'pt': 'noite','pt_': '-----', 'en_': '-----'},
    3: {'en': 'afternoon', 'pt': 'tarde', 'pt_': '---------', 'en_': '-----'},
    4: {'en': 'morning', 'pt': 'manha', 'pt_': '-------', 'en_': '-----'},
    5: {'en': 'together', 'pt': 'juntos', 'pt_': '--------','en_': '------'},
    6: {'en': 'theirs', 'pt': 'deles', 'pt_': '------', 'en_': '-----'},
    7: {'en': 'his', 'pt': 'dele', 'pt_': '---', 'en_': '----'}, 8: {'en': 'hers', 'pt': 'dela', 'pt_': '----','en_': '----'},
    9: {'en': 'he', 'pt': 'ele', 'pt_': '--', 'en_': '---'},
    10: {'en': 'her', 'pt': 'dela', 'pt_': '---', 'en_': '---'}, 11: {'en': 'them', 'pt': 'eles', 'pt_': '----', 'en_': '----'},
    12: {'en': 'me', 'pt': 'eu', 'pt_': '--', 'en_': '--'}, 13: {'en': 'my', 'pt': 'meu', 'pt_': '--', 'en_': '---'},
    14: {'en': 'with', 'pt': 'com', 'pt_': '----', 'en_': '---'},15: {'en': 'where', 'pt': 'onde', 'pt_': '-----', 'en_': '----'},
    16: {'en': 'how much', 'pt': 'quanto', 'pt_': '--------', 'en_': '------'},
    17: {'en': 'I want', 'pt': 'eu quero', 'pt_': '------', 'en_': '--------'},
    18: {'en': 'we want', 'pt': 'nos queremos', 'pt_': '-------', 'en_': '------------'},
    19: {'en': 'how much?', 'pt': 'quanto?', 'pt_': '---------', 'en_': '-------'},
    20: {'en': 'seriously', 'pt': 'serio', 'pt_': '---------', 'en_': '-----'},
    21: {'en': 'parents', 'pt': 'pais', 'pt_': '-------', 'en_': '----'},
    22: {'en': 'brother ', 'pt': 'irmão', 'pt_': '--------', 'en_': '-----'},
    23: {'en': 'sister', 'pt': 'irmã', 'pt_': '------', 'en_': '----'},
    24: {'en': 'grandmother', 'pt': 'avó', 'pt_': '-----------', 'en_': '---'},
    25: {'en': 'grandfather', 'pt': 'avô', 'pt_': '-----------', 'en_': '---'},
    26: {'en': 'aunt', 'pt': 'tia', 'pt_': '----', 'en_': '---'},
    27: {'en': 'cousin', 'pt': 'primo', 'pt_': '------', 'en_': '-----'},
    28: {'en': 'uncle', 'pt': 'tio', 'pt_': '-----', 'en_': '---'}, 29: {'en': 'good', 'pt': 'bom', 'pt_': '----', 'en_': '---'},
    30: {'en': 'bad', 'pt': 'ruim', 'pt_': '---', 'en_': '----'},
    31: {'en': 'terrible', 'pt': 'terrivel', 'pt_': '--------', 'en_': '--------'},
    32: {'en': 'horrible', 'pt': 'horrivel', 'pt_': '--------', 'en_': '--------'},
    33: {'en': 'reading', 'pt': 'lendo', 'pt_': '-------', 'en_': '-----'},
    34: {'en': 'writing', 'pt': 'escrevendo', 'pt_': '-------', 'en_': '----------'},
    35: {'en': 'running', 'pt': 'correndo', 'pt_': '-------', 'en_': '--------'},
    36: {'en': 'playing', 'pt': 'brincando', 'pt_': '-------', 'en_': '---------'}
}