export const padraoDict = {
    1: {'pt': 'day', 'en': 'dia', 'pt_': '---', 'en_': '---'},
    2: {'pt': 'night', 'en': 'noite','pt_': '-----', 'en_': '-----'},
    3: {'pt': 'afternoon', 'en': 'tarde', 'pt_': '---------', 'en_': '-----'},
    4: {'pt': 'morning', 'en': 'manha', 'pt_': '-------', 'en_': '-----'},
    5: {'pt': 'together', 'en': 'juntos', 'pt_': '--------','en_': '------'},
    6: {'pt': 'theirs', 'en': 'deles', 'pt_': '------', 'en_': '-----'},
    7: {'pt': 'his', 'en': 'dele', 'pt_': '---', 'en_': '----'}, 8: {'pt': 'hers', 'en': 'dela', 'pt_': '----','en_': '----'},
    9: {'pt': 'he', 'en': 'ele', 'pt_': '--', 'en_': '---'},
    10: {'pt': 'her', 'en': 'ela', 'pt_': '---', 'en_': '---'}, 11: {'pt': 'them', 'en': 'eles', 'pt_': '----', 'en_': '----'},
    12: {'pt': 'me', 'en': 'eu', 'pt_': '--', 'en_': '--'}, 13: {'pt': 'my', 'en': 'meu', 'pt_': '--', 'en_': '---'},
    14: {'pt': 'with', 'en': 'com', 'pt_': '----', 'en_': '---'},15: {'pt': 'where', 'en': 'onde', 'pt_': '-----', 'en_': '----'},
    16: {'pt': 'how much', 'en': 'quanto', 'pt_': '--------', 'en_': '------'},
    17: {'pt': 'I want', 'en': 'eu quero', 'pt_': '------', 'en_': '--------'},
    18: {'pt': 'we want', 'en': 'nos queremos', 'pt_': '-------', 'en_': '------------'},
    19: {'pt': 'how much?', 'en': 'quanto?', 'pt_': '---------', 'en_': '-------'},
    20: {'pt': 'seriously', 'en': 'serio', 'pt_': '---------', 'en_': '-----'},
    21: {'pt': 'parents', 'en': 'pais', 'pt_': '-------', 'en_': '----'},
    22: {'pt': 'brother ', 'en': 'irmão', 'pt_': '--------', 'en_': '-----'},
    23: {'pt': 'sister', 'en': 'irmã', 'pt_': '------', 'en_': '----'},
    24: {'pt': 'grandmother', 'en': 'avó', 'pt_': '-----------', 'en_': '---'},
    25: {'pt': 'grandfather', 'en': 'avô', 'pt_': '-----------', 'en_': '---'},
    26: {'pt': 'aunt', 'en': 'tia', 'pt_': '----', 'en_': '---'},
    27: {'pt': 'cousin', 'en': 'primo', 'pt_': '------', 'en_': '-----'},
    28: {'pt': 'uncle', 'en': 'tio', 'pt_': '-----', 'en_': '---'}, 29: {'pt': 'good', 'en': 'bom', 'pt_': '----', 'en_': '---'},
    30: {'pt': 'bad', 'en': 'ruim', 'pt_': '---', 'en_': '----'},
    31: {'pt': 'terrible', 'en': 'terrivel', 'pt_': '--------', 'en_': '--------'},
    32: {'pt': 'horrible', 'en': 'horrivel', 'pt_': '--------', 'en_': '--------'},
    33: {'pt': 'reading', 'en': 'lendo', 'pt_': '-------', 'en_': '-----'},
    34: {'pt': 'writing', 'en': 'escrevendo', 'pt_': '-------', 'en_': '----------'},
    35: {'pt': 'running', 'en': 'correndo', 'pt_': '-------', 'en_': '--------'},
    36: {'pt': 'playing', 'en': 'brincando', 'pt_': '-------', 'en_': '---------'}
}